title: ASPIRE Lab
description: Autonomous Systems using AI for Perception, Intelligence, and Robotic Exploration
url: "https://aspirelabiith.github.io"
baseurl: ""
remote_theme: alshedivat/al-folio@main

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
